export enum ParcelStatus {
  PICKING_UP = 'PICKING_UP',
  PICKED_UP = 'PICKED_UP',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  CANCELED = 'CANCELED',
  WAITING_FOR_PAYMENT = 'WAITING_FOR_PAYMENT'
}
