export enum TaskStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  RETURNING_TO_STATION = 'RETURNING_TO_STATION',
  ASSIGNED = 'ASSIGNED',
  AT_CHECKPOINT = 'AT_CHECKPOINT'
}
